# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Sadovod' do

pod 'SCLAlertView-Objective-C'
pod "MagicalRecord"
pod "AFNetworking", "~> 2.0"
pod 'Motis', '~>1.3.0'
pod 'SVPullToRefresh'
pod 'SDWebImage', '~>3.7'
pod 'AFNetworking+ImageActivityIndicator', '~> 1.0'

end

target 'SadovodTests' do

end

target 'SadovodUITests' do

end

